controller_names:
  - manipulator_ur10_controller
    #  - hand_controller

manipulator_ur10_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - ur10_shoulder_pan_joint
    - ur10_shoulder_lift_joint
    - ur10_elbow_joint
    - ur10_wrist_1_joint
    - ur10_wrist_2_joint
    - ur10_wrist_3_joint

# endeffector_controller:
#   action_ns: gripper_action
#   type: GripperCommand
#   default: true
#   joints:
#     - panda_finger_joint1
#     - panda_finger_joint2
