/**:
  ros__parameters:
    start_position:
      joints:
        - ur10_shoulder_pan_joint
        - ur10_shoulder_lift_joint
        - ur10_elbow_joint
        - ur10_wrist_1_joint
        - ur10_wrist_2_joint
        - ur10_wrist_3_joint
      values:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
